# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
                ('ftime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('like', '喜欢'), ('superlike', '超级喜欢'), ('dislike', '不喜欢'), ('blacklist', '拉黑')], max_length=10, verbose_name='滑动状态')),
                ('uid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('stime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
